sudo: required

language: bash

dist: trusty

services:
  - docker

script:
  - docker build -f Dockerfile . -t panchajanya1999/archlinux:latest
  - echo "$password" | docker login -u "panchajanya1999" --password-stdin
  - docker push panchajanya1999/archlinux:latest
