name: Archlinux docker builder

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check Out v4
      uses: actions/checkout@v4

    - name: Build docker
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      shell: bash
      run: |
         docker build -f Dockerfile . -t jprimero15/archlinux-docker:latest
         echo "$DOCKER_TOKEN" | docker login -u "jprimero15" --password-stdin
         docker push jprimero15/archlinux-docker:latest
